LimeChain/goscale

empty.go
empty_test.go

feat: add empty

---

codec.go
empty.go
empty_test.go
option.go
option_test.go
result.go
result_test.go

Fixes #13 
TODOs left:
https://github.com/golang/go/issues/54393
https://github.com/golang/go/issues/50741
**Checklist**

feat: add result

---

types.go

Fixes [#25](https://github.com/LimeChain/goscale/issues/25)
**Checklist**

Add SCALE String helper representation

---

result.go
result_test.go

refactor(result): remove decode type and use T

---

README.md
option.go
option_test.go

* add `OptionBool` as per substrate implementation
**Checklist**

feat: add Substrate's OptionBool

---

result.go

refactor(result): value of T

---

option.go
option_test.go

feat(option-bool): handle invalid byte representation

---

boolean.go
boolean_test.go
option_test.go
result_test.go

feat(bool): check byte

---

sequence.go
sequence_test.go

feat(sequence): generic decode

---

fixed_length_test.go

More renaming

---

option.go
result.go
sequence_test.go

Export the fields from the Result type. Small change in the Option

---

README.md
boolean.go
boolean_test.go
common.go
empty.go
empty_test.go
fixed_length.go
fixed_length_test.go
length_compact.go
length_compact_test.go
option.go
option_test.go
result.go
result_test.go
sequence.go
sequence_test.go
varying_data.go
varying_data_test.go

feat(encodable): Bytes() func

---

.github/workflows/test.yaml

ci: bump go version

---

README.md
boolean.go
codec.go
dictionary.go
sequence.go
sequence_test.go
tuple.go
tuple_test.go

Fixes [#5](https://github.com/LimeChain/goscale/issues/5)
**Checklist**

Tuple type impl

---

README.md
common.go
dictionary.go
fixed_length.go
length_compact.go
length_compact_test.go
option_test.go
result_test.go
sequence.go
sequence_test.go
tuple.go
tuple_test.go
varying_data_test.go

* underlying type is U128
Fixes #47 
**Checklist**

refactor: merge Compact & CompactU128

---

README.md
codecov.yaml

repo: coverage status badge

---

common.go
dictionary.go
sequence.go
varying_data.go

adds util functions

---

option.go
option_test.go
result.go
result_test.go
varying_data.go

Add initializer to the Option[T] type

---

sequence.go

Add utility functions to Sequence/FixedSequence types

---

common.go
option_test.go
result_test.go

more convenient Compact conversion of any numeric type

---

common.go
dictionary.go
sequence.go
tuple.go

Add support for numeric scale types in the ToCompact utility function

---

numeric_extended.go
option.go

Extend numeric types with operations handling overflows/underflows

---

numeric_extended.go

Add support for more math functions

---

numeric_extended.go

Extend with checked math functions

---

math.go
math_test.go

feat(math): minU32
